@startuml DiagramaN0_RF2V2_AdministrarSistema

skinparam actorStyle awesome
left to right direction

skinparam DefaultFontColor black
skinparam BackgroundColor white

skinparam usecase {
    BackgroundColor<<Auth>> #8A6D3B
    BorderColor black
    FontColor white
}

actor "Usuario" as Usuario

note top of Usuario
  Representa todos los roles:
  Guardia | Supervisor
  Centralista | Jefe Logistica/Operacion
end note

rectangle "Sistema TekMess - SNAAR\nAdministrar Sistema (RF-02V2)" #White {

    usecase "Iniciar Sesion"        as UC1 <<Auth>>
    usecase "Cambiar Contrasena"    as UC2 <<Auth>>
    usecase "Recuperar Contrasena"  as UC3 <<Auth>>
    usecase "Validar Credenciales"  as UC4 <<Auth>>

}

Usuario--UC1
Usuario--UC2
Usuario--UC3

UC1 ..> UC4 : <<include>>
UC2 ..> UC4 : <<include>>
UC1 ..> UC2 : <<extend>>\n(primer acceso)
UC1 ..> UC3 : <<extend>>\n(olvido contrasena)

'Elaborado Grupo 6 - ADSW ESPE - 2026
@enduml
