@startuml DiagramaN0General

skinparam actorStyle awesome
left to right direction

skinparam DefaultFontColor black
skinparam BackgroundColor white

skinparam usecase {
    BackgroundColor<<Admin>>    #A94442
    BackgroundColor<<Auth>>     #8A6D3B
    BackgroundColor<<Reporte>>  #3C763D
    BorderColor black
    FontColor white
}

actor Usuario
actor Guardia
actor Centralista
actor Supervisor
actor "Jefe Operativo/Logistica" as Jefe

Usuario--Guardia
Usuario--Centralista
Usuario--Supervisor
Usuario--Jefe

rectangle "Sistema TekMess - SNAAR" #White {

    usecase "Gestionar Empleados"        as RF1 <<Admin>>
    usecase "Administrar Sistema"        as RF2 <<Auth>>
    usecase "Generar Reporte Analitico"  as RF3 <<Reporte>>

}

Jefe--RF1
Usuario--RF2
Jefe--RF3
Supervisor--RF3

RF1 ..> RF2 : <<include>>
RF3 ..> RF1 : <<include>>
RF3 ..> RF2 : <<include>>

'Elaborado Grupo 6 - ADSW ESPE - 2026
@enduml
