@startuml

skinparam actorStyle awesome
left to right direction

skinparam DefaultFontColor black
skinparam BackgroundColor white

actor "Jefe Operativo/Logística" as Jefe

rectangle "SNAAR - GESTIONAR EMPLEADOS (GE)" #White {
    
    
    usecase "Crear Empleado" as UC_Crear
    usecase "Generar Credenciales de Acceso" as UC_Generar
    usecase "Asignar relaciones laborales" as UC_Asignar
    usecase "Habilitar chat de mensajería" as UC_Habilitar
    usecase "Editar Empleado" as UC_Editar
    usecase "Eliminar Empleado" as UC_Eliminar

}

' Uniones de actores a casos de uso

Jefe--UC_Crear
Jefe--UC_Asignar
Jefe--UC_Editar
Jefe--UC_Eliminar


UC_Crear ..> UC_Generar : <<include>>
UC_Crear ..> UC_Asignar : <<include>>
UC_Asignar ..> UC_Habilitar : <<include>>

note right of UC_Crear
Datos mínimos según interfaz:
- Cedula
- Nombre
- Edad
- Correo

end note

'Elaborado David Pilaguano - 2026-05-05 
@enduml