@startuml

skinparam actorStyle awesome
left to right direction

skinparam DefaultFontColor black
skinparam BackgroundColor white

actor "Jefe Operativo/Logística" as Jefe

rectangle "SNAAR - GESTIONAR EMPLEADOS (GE)" #White {
    
    
    usecase "Crear Empleado" as UC_Crear
    usecase "Asignar relaciones laborales" as UC_Asignar
    usecase "Editar Empleado" as UC_Editar
    usecase "Eliminar Empleado" as UC_Eliminar
    usecase "Consultar Empleados" as UC_Consultar

}

' Uniones de actores a casos de uso

Jefe--UC_Crear
Jefe--UC_Asignar
Jefe--UC_Editar
Jefe--UC_Eliminar
Jefe--UC_Consultar

UC_Crear ..> UC_Asignar : <<include>>

note right of UC_Crear
Datos mínimos según interfaz:
- Cedula
- Nombre
- Edad
- Correo

end note

'Elaborado David Pilaguano - 2026-05-05 
@enduml