@startuml DiagramaN0_RF1_GestionarEmpleados

skinparam actorStyle awesome
left to right direction

skinparam DefaultFontColor black
skinparam BackgroundColor white

skinparam usecase {
    BackgroundColor<<Admin>> #A94442
    BorderColor black
    FontColor white
}

actor "Jefe Operativo/\nLogistica" as Jefe

rectangle "Sistema TekMess - SNAAR\nGestionar Empleados (RF-01)" #White {

    usecase "Crear Empleado"              as UC1 <<Admin>>
    usecase "Editar Empleado"             as UC2 <<Admin>>
    usecase "Eliminar Empleado"           as UC3 <<Admin>>
    usecase "Consultar Empleados"         as UC4 <<Admin>>
    usecase "Validar Datos\ndel Empleado" as UC5 <<Admin>>
    usecase "Generar\nCredenciales"       as UC6 <<Admin>>

}

Jefe--UC1
Jefe--UC2
Jefe--UC3
Jefe--UC4

UC1 ..> UC5 : <<include>>
UC2 ..> UC5 : <<include>>
UC1 ..> UC6 : <<include>>

'Elaborado Grupo 6 - ADSW ESPE - 2026
@enduml
